### ISSUE TITLE
进入函数内部不是next指令嘛

### ISSUE THREAD

**Issue by ChenZiHong-Gavin** [hewei-nju/OSLab#1]

**Comment by WeiHea** [comment]
是的，我参考的 gdb 调试汇编的手册有讲到：
* `n[ext]i num` 是用来调试进行汇编的命令，gdb 调试指南为 [gdb debugger assembly](https://web.cecs.pdx.edu/~apt/cs322/gdb.pdf)
* 然后我有尝试next命令，确实可以实现相关需求。
* 我在 gdb 的 [bug database](https://sourceware.org/bugzilla/) 中有找到相同的问题 https://sourceware.org/bugzilla/show_bug.cgi?id=21906
